# 根据仓库结构添加标签规则
frontend:
  - frontend/**/*

backend:
  - backend/**/*

website:
  - website/**/*

docs:
  - docs/**/*

workflows:
  - .github/workflows/**/*

helm-charts:
  - helm-charts/**/*

# 内部变更标签
internal:
  - .github/**
  - scripts/**
  - .gitignore
  - .pre-commit-config.yaml

# 常见变更类型标签可在PR中手动添加
# breaking
# security
# feature
# bug
# refactor
# upgrade
# enhancement