name: 文档构建与部署

on:
  push:
    branches:
      - main
    paths:
      - 'website/**'
      - '.github/workflows/deploy-docs.yml'
  workflow_dispatch:

jobs:
  redirect-to-docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: 触发 docker-build 工作流
        run: |
          echo "文档构建已迁移到 docker-build.yml 工作流中"
          echo "正在触发 docker-build 工作流..."
          
      - name: 触发工作流
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: docker-build.yml
          token: ${{ secrets.GITHUB_TOKEN }} 