name: Deploy to Staging

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on:
      - self-hosted
      - staging
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Doppler environment
        run: doppler setup --silent --project quick-forge-ai --config stg
        env:
          DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN }}

      - name: Docker Compose Build (with Doppler env)
        run: doppler run --mount=false -- docker compose -f docker-compose.yml build
        env:
          DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN }}

      - name: Docker Compose Up (with Doppler env)
        run: doppler run --mount=false -- docker compose -f docker-compose.yml up -d
        env:
          DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN }}