name: Deploy to Staging

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on:
      - self-hosted
      - staging
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Doppler environment
        run: |
          doppler setup --silent --project quick-forge-ai --config stg
          doppler run -- docker compose up -d
        env:
          DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN }}
