name: 构建和部署文档网站

on:
  push:
    branches:
      - main
    paths:
      - 'website/**'
      - '.github/workflows/deploy-docs.yml'
  workflow_dispatch:

jobs:
  build-and-push-docs:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 设置 Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: 登录到 Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: 登录到 GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 获取 Docker 元数据
        id: metadata-docs
        uses: docker/metadata-action@v5.5.1
        with:
          images: |
            docker.io/${{ github.repository_owner }}/quick-forge-ai-docs
            ghcr.io/${{ github.repository_owner }}/quick-forge-ai-docs
          tags: |
            type=sha,format=short
            type=raw,value=latest,enable={{is_default_branch}}

      - name: 构建并推送文档镜像
        uses: docker/build-push-action@v5
        with:
          context: ./website
          file: ./website/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.metadata-docs.outputs.tags }}
          labels: ${{ steps.metadata-docs.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          provenance: true

  deploy-docs:
    needs: build-and-push-docs
    runs-on: ubuntu-latest
    # 如果你有自己的服务器，这里可以替换为 self-hosted
    # runs-on:
    #   - self-hosted
    #   - production
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      # 如果要部署到服务器，可以使用 SSH 执行部署命令
      # - name: 部署到服务器
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: ${{ secrets.DOCS_HOST }}
      #     username: ${{ secrets.DOCS_USERNAME }}
      #     key: ${{ secrets.DOCS_SSH_KEY }}
      #     script: |
      #       cd /path/to/deployment
      #       docker pull ghcr.io/${{ github.repository_owner }}/quick-forge-ai-docs:latest
      #       docker-compose down
      #       docker-compose up -d

      # 如果要部署到 GitHub Pages，可以使用以下步骤
      - name: 设置 Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: 安装依赖
        working-directory: ./website
        run: npm ci
        
      - name: 构建文档
        working-directory: ./website
        run: |
          npm run build
          npm run postbuild
          
      - name: 部署到 GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./website/.next/server/app
          cname: docs.your-domain.com  # 替换为你的域名 