name: Docker Build and Push

on:
  schedule:
    - cron: '30 2 * * *'
  push:
    branches:
      - main
      - release-*
    tags:
      - 'v*.*.*'
      - 'v*.*.*-*'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Log in to AliYun Docker Hub
        uses: docker/login-action@v3
        with:
          registry: registry.cn-hangzhou.aliyuncs.com
          username: ${{ secrets.ALIREGISTRY_USERNAME }}
          password: ${{ secrets.ALIREGISTRY_TOKEN }}

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Docker metadata for backend
        id: metadata-backend
        uses: docker/metadata-action@v5.5.1
        with:
          images: |
            docker.io/${{ github.repository_owner }}/quick-forge-ai-backend
            registry.cn-hangzhou.aliyuncs.com/${{ github.repository_owner }}/quick-forge-ai-backend
            ghcr.io/${{ github.repository_owner }}/quick-forge-ai-backend
          tags: |
            type=ref,event=tag
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern=v{{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha

      - name: Build backend
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.metadata-backend.outputs.tags }}
          labels: ${{ steps.metadata-backend.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          provenance: true

      - name: Get Docker metadata for frontend
        id: metadata-frontend
        uses: docker/metadata-action@v5.5.1
        with:
          images: |
            docker.io/${{ github.repository_owner }}/quick-forge-ai-frontend
            registry.cn-hangzhou.aliyuncs.com/${{ github.repository_owner }}/quick-forge-ai-frontend
            ghcr.io/${{ github.repository_owner }}/quick-forge-ai-frontend
          tags: |
            type=ref,event=tag
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern=v{{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha

      - name: Build frontend
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.metadata-frontend.outputs.tags }}
          labels: ${{ steps.metadata-frontend.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          provenance: true

      - name: Clean up Docker
        if: always()
        run: docker system prune -f