name: Spell Check with Typos

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  spellcheck:
    name: Spell Check
    runs-on: ubuntu-latest
    concurrency:
      group: spellcheck-${{ github.ref }}
      cancel-in-progress: true
    timeout-minutes: 10
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Spell Check
        uses: crate-ci/typos@v1
        with:
          config: _typos.toml
          write_changes: false

      - name: Test Configuration
        if: ${{ always() }}
        run: |
          echo "Testing typos configuration..."
          if [ -f _typos.toml ]; then
            echo "✅ Configuration file exists"
            typos --dump-config - | grep -q "files.extend-exclude" && echo "✅ Configuration loaded correctly" || echo "❌ Configuration not loaded"
          else
            echo "❌ Configuration file not found"
            exit 1
          fi